ejemplo1: ejemplo1.c	
	gcc -o ejemplo1 ejemplo1.c

ejemplo2: ejemplo2.c
	gcc -o ejemplo2 ejemplo2.c

ejemplo3: ejemplo3.c
	gcc -o ejemplo3 ejemplo3.c

ejemplo4: ejemplo4.c
	gcc -o ejemplo4 ejemplo4.c

ejemplo5: ejemplo5.c
	gcc -o ejemplo5 ejemplo5.c

ejemplo6: ejemplo6.c
	gcc -o ejemplo6 ejemplo6.c

clean:
	rm -f ejemplo1 ejemplo2 ejemplo3 ejemplo4 ejemplo5 ejemplo6